name: Enforce Sovereign IP Marks

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: python -m pip install --upgrade pip
      - name: Run ipmarks runner
        run: |
          python3 ops/ipmarks/runner.py
      - name: Check for unexpected changes
        run: |
          git --no-pager status --porcelain
          if [ -n "$(git --no-pager status --porcelain)" ]; then
            echo "Repository modified by runner. Please commit runner changes.";
            git --no-pager status --porcelain;
            exit 1;
          fi
      - name: Setup Node and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install --frozen-lockfile
      - name: Build site
        run: pnpm build
      - name: Run pytest (idempotency)
        run: |
          python -m pip install pytest
          pytest ops/tests -q
